-- return {
--   {
--     "nvim-telescope/telescope-file-browser.nvim",
--     dependencies = { "nvim-telescope/telescope.nvim", "nvim-lua/plenary.nvim" },
--   },
--   {
--     "nvim-telescope/telescope.nvim",
--     branch = "0.1.x",
--     dependencies = {
--       "nvim-lua/plenary.nvim",
--       { "nvim-telescope/telescope-fzf-native.nvim", build = "make" },
--       "nvim-tree/nvim-web-devicons",
--     },
--     config = function()
--       local telescope = require("telescope")
--       local actions = require("telescope.actions")
--
--       telescope.setup({
--         defaults = {
--           path_display = { "truncate " },
--           mappings = {
--             i = {
--               ["<C-k>"] = actions.move_selection_previous, -- move to prev result
--               ["<C-j>"] = actions.move_selection_next, -- move to next result
--             },
--           },
--         },
--         pickers = {
--           buffers = {
--             sort_mru = true,
--             ignore_current_buffer = true,
--           },
--         },
--       })
--
--       telescope.load_extension("fzf")
--       telescope.load_extension("file_browser")
--       telescope.load_extension("noice")
--
--       -- set keymaps
--       local keymap = vim.keymap -- for conciseness
--
--       keymap.set("n", "<leader>ff", "<cmd>Telescope find_files<cr>", { desc = "Fuzzy find files in cwd" })
--       keymap.set("n", "<leader>fr", "<cmd>Telescope oldfiles<cr>", { desc = "Fuzzy find recent files" })
--       keymap.set("n", "<leader>fs", "<cmd>Telescope live_grep<cr>", { desc = "Find string in cwd" })
--       keymap.set("n", "<leader>fp", "<cmd>Telescope neovim-project discover<cr>", { desc = "Find project" })
--       -- live grep in current buffer
--       keymap.set(
--         "n",
--         "<leader>fb",
--         "<cmd>Telescope current_buffer_fuzzy_find<cr>",
--         { desc = "Fuzzy find in current buffer" }
--       )
--       keymap.set("n", "<leader>fc", "<cmd>Telescope grep_string<cr>", { desc = "Find string under cursor in cwd" })
--       keymap.set("n", "<leader><return>", "<cmd>Telescope buffers<cr>", { desc = "Find buffers" })
--
--       keymap.set("n", "<leader><space>", ":Telescope file_browser path=%:p:h select_buffer=true<CR>")
--     end,
--   },
-- }
return {}
